### ISSUE TITLE
Performance compare

### ISSUE THREAD

**Issue by Romick2005** [OP-Engineering/op-sqlite#193]
Would be interesting to compare performance with https://github.com/margelo/react-native-nitro-sqlite.

**Comment by ospfranco** [comment]
PRs are welcome, all the benchmark code is in the example app, so it should only be a matter of adding nitro-sqlite and doing the large query.

**Comment by ospfranco** [comment]
Got curious decided to try it, I had to create a new expo app since it seems nitro doesn't work with yarn workspaces in the example app. However, the results are as I expected, nothing will be faster than binding directly to JSI C++ code:

![OSP 000562](https://github.com/user-attachments/assets/da5b29f9-997e-4eec-99fd-3f6d30a361c9)
