### ISSUE TITLE
1.0.4 is missing podspec/ArrayBuffer support is botched

### ISSUE THREAD

**Issue by nikgraf** [OP-Engineering/op-sqlite#2]
I installed op-sqlite on this app: https://github.com/serenity-kit/Serenity/tree/main/apps/app

I follow the usual steps:
1. build simulator build with eas
2. download the build and install it on the simulator

Now receiving this error on the console and in the App:
<img width="404" alt="Screenshot 2023-11-10 at 09 10 44" src="https://github.com/OP-Engineering/op-sqlite/assets/223045/75be13ad-4ee9-4fdf-a9ba-d1666f3bb9ac">

When I use react-native-quick-sqlite it works: https://github.com/serenity-kit/Serenity/pull/856/commits/906e3daaf3e02078b9ce989996f33d3514654001

I don't know what's different, but seems like eas is not including the package in the build? Could it be that react-native packages are only picked up if they are prefixed with react-native? Otherwise I'm not sure what could be different

**Comment by ospfranco** [comment]
Weird, let me give it a try in a fresh project.

**Comment by ospfranco** [comment]
I botched the podspec. Released a new version `1.0.6` can you update and install the pods again?

**Comment by nikgraf** [comment]
on it

**Comment by nikgraf** [comment]
Now I'm getting these errors:

```sh
[Error: Exception in HostFunction: <unknown>]
```

The same statements works in sql.js on the web and in `react-native-quick-sqlite`

**Comment by nikgraf** [comment]
I did a bit of debugging and this one statement is causing it to fail:

```
export const createOrReplaceDocument = ({
  documentId,
  name,
  content,
}: {
  documentId: string;
  name?: string;
  content?: Uint8Array;
  triggerRerender?: boolean;
}) => {
  sql.execute(`INSERT OR REPLACE INTO ${table} VALUES (?, ?, ?);`, [
    documentId,
    name || null,
    content || null,
  ]);
};
```

My best guess it's the content being a Uint8Array. Everything else works fine

**Comment by ospfranco** [comment]
Let me take a look

**Comment by ospfranco** [comment]
Ok, found the issue. The problem is that `Uint8Array` is NOT an `ArrayBuffer`, an ArrayBuffer is a view on top of the different typed arrays. On `quick-sqlite` these values where just being [replaced by nulls](https://github.com/ospfranco/react-native-quick-sqlite/blob/main/cpp/JSIHelper.cpp#L124C1-L124C1) which means your data is not being persisted.

I apologize for this, initial ArrayBuffer support was not added by me and at the time didn't understand the semantics of it. On `op-sqlite` I actually throw an error instead of silently trying to insert data (also found the problem with how I was throwing the exception and more explicit description will be thrown in the next version).

In order for you to insert blob data into SQLite you have to wrap `Uint8Array` into an ArrayBuffer:

```ts
let buffer = new ArrayBuffer(24);
var content = new Uint8Array(buffer, 4, 16);
crypto.getRandomValues(content);

db.execute(`INSERT OR REPLACE INTO BlobTable VALUES (?, ?, ?);`, [
  1,
  'myTestBlob',
   buffer,
]);
```

**Comment by ospfranco** [comment]
Does `.buffer` work on all TypedArrays? If so then yeah, why not, we could do some validation on the JS side before sending to native.

**Comment by ospfranco** [comment]
Done. Updated the README as well:

```ts
const uint8 = new Uint8Array(2);
uint8[0] = 42;

db.execute(`INSERT OR REPLACE INTO BlobTable VALUES (?, ?);`, [1, uint8]);

const result = db.execute('SELECT content FROM BlobTable');

const finalUint8 = new Uint8Array(result.rows!._array[0].content);
expect(finalUint8[0]).to.equal(42);
```

**Comment by nikgraf** [comment]
awesome, cool stuff! will test it tomorrow

**Comment by nikgraf** [comment]
works like a charm! switched over to op-sqlite :)
