### ISSUE TITLE
sqlite extensions

### ISSUE THREAD

**Issue by Zoxive** [OP-Engineering/op-sqlite#30]
Curious if theres any one else interested in having the ability to load sqlite extensions?

https://www.sqlite.org/loadext.html

(Personally im looking to experiment with https://github.com/vlcn-io/cr-sqlite)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/OP-Engineering) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/OP-Engineering/op-sqlite/issues/30">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/OP-Engineering/op-sqlite/issues/30/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/OP-Engineering/op-sqlite/issues/30/pledge.svg">
</picture>
</a>

**Comment by ospfranco** [comment]
No idea how to load external extensions, I guess if you manage to compile it and load it as a dylib you can try to enable it on runtime. You will have to try it yourself and maybe I will get to it one day

**Comment by ezra-en** [comment]
I've been looking into this since `react-native-quick-sqlite`, and I was wondering whether it'd be possible to simply expose `sqlite3_load_extension()`?
[`sqlite-android`](https://github.com/requery/sqlite-android) appears to support it by using [just that](https://github.com/requery/sqlite-android/blob/4fb4458c843d53d7bdf6047346724e45e612ea0a/sqlite-android/src/main/jni/sqlite/android_database_SQLiteConnection.cpp#L903).

In case you didn't know @Zoxive, [Expo has been working with Matt](https://expo.dev/changelog/2023/08-10-cr-sqlite) on getting proper bindings and integration between `cr-sqlite` and `expo-sqlite`!

I'm personally looking to extend FTS5 with custom tokenizers, but I don't know nearly enough C++ to figure it out 😅

**Comment by ospfranco** [comment]
exposing `sqlite3_load_extension` should be easy, the compilation step not so much, but that will be left as an exercise to the reader I guess. Each to his own.

**Comment by sutyum** [comment]
sounds good! lots of great plugins to choose from. For instance their vector search plugin would be great to do local vector search for ai apps - and no good way to use this plugin in a react native project yet (in a convenient way).

**Comment by abdelhameedhamdy** [comment]
I think exposing ```sqlite3_load_extension``` would be a great option, as there are awesome extensions for sqlite, hope to see it soon.

**Comment by ospfranco** [comment]
Sorry, busy with paid work, if anyone is willing to sponsor the work I might be able to take a look sooner

**Comment by ospfranco** [comment]
I've created a funding goal for this issue, once it is reached I will take a look into it

https://polar.sh/OP-Engineering/op-sqlite/issues/17
