### ISSUE TITLE
Support other collates

### ISSUE THREAD

**Issue by SrMouraSilva** [OP-Engineering/op-sqlite#66]
Hello, thank you for this awesome project.

I would like to know if it is possible to use other collates.

SQLite has by default these three collates [binary, nocase, rtrim](https://www.sqlite.org/datatype3.html#collating_sequences). In my case, I would like to sort text that has accent. Android SQL has [UNICODE and LOCALIZED](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase#localized-collation---order-by) support.

By the way, use default Android SQLite instead of op-sqlite would be just like a crazy decision due the amount of benefits using op-sqlite. :)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/OP-Engineering) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/OP-Engineering/op-sqlite/issues/66">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/OP-Engineering/op-sqlite/issues/66/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/OP-Engineering/op-sqlite/issues/66/pledge.svg">
</picture>
</a>

**Comment by ospfranco** [comment]
Interesting, never used collation functions. I guess I could expose a way to call the collation register function, although that sounds complicated and slow. I guess you could also monkey-patch the sources to register your own C function.

Unfortunately, it is not possible to use the embedded Android SQLite from C++, only from Java. It is also a bad idea since older phones have really old versions with a lot of incompatibilities and each vendor modifies the SQLite implementation causing a lot of errors.

**Comment by ospfranco** [comment]
So, just to be clear, not going to implement this myself. This is niche. If you want it, you will have to implement it yourself or do a heavy sponsoring.
